import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const jobs=[
 {id:1,title:'Content Writer for B2B SaaS Blog',company:'Northstar Labs',type:'Freelance',location:'Remote · Worldwide',pay:'$800–1,200 / project',skill:'Writing',fresh:'2h ago',tag:'Featured'},
 {id:2,title:'Short-form Video Editor for Creator Brand',company:'Field Notes Studio',type:'Contract',location:'Remote · Americas',pay:'$35–50 / hour',skill:'Video',fresh:'5h ago',tag:'New'},
 {id:3,title:'No-code Landing Page Designer',company:'Morrow Commerce',type:'Part-time',location:'Remote · India',pay:'₹35k–55k / month',skill:'Design',fresh:'Yesterday',tag:'Popular'},
 {id:4,title:'Virtual Assistant for Boutique Agency',company:'Quietly Good Co.',type:'Freelance',location:'Remote · Asia-Pacific',pay:'$18–24 / hour',skill:'Support',fresh:'Yesterday',tag:'New'},
 {id:5,title:'SEO Researcher for Editorial Team',company:'Signal House',type:'Contract',location:'Remote · Worldwide',pay:'$600–900 / month',skill:'Marketing',fresh:'2d ago',tag:'Verified'},
 {id:6,title:'React Developer for Product Sprint',company:'Copperline',type:'Freelance',location:'Remote · Europe',pay:'€45–65 / hour',skill:'Development',fresh:'2d ago',tag:'Verified'}
];
const skills=['All roles','Writing','Design','Development','Marketing','Video','Support'];
function App(){
 const [query,setQuery]=useState(''); const [skill,setSkill]=useState('All roles'); const [email,setEmail]=useState(''); const [subscribed,setSubscribed]=useState(false);
 const filtered=useMemo(()=>jobs.filter(j=>(skill==='All roles'||j.skill===skill)&&[j.title,j.company,j.location,j.skill].join(' ').toLowerCase().includes(query.toLowerCase())),[query,skill]);
 return <div className="app"><header className="nav"><a className="brand" href="#top"><span className="brand-mark">FJ</span><span>Freelance<br/><em>Job Alerts</em></span></a><nav><a href="#jobs">Browse jobs</a><a href="#how">How it works</a><a href="#newsletter">Get alerts</a></nav><button className="nav-button" onClick={()=>document.querySelector('#newsletter').scrollIntoView({behavior:'smooth'})}>Join free <span>↗</span></button></header>
 <main id="top"><section className="hero"><div className="eyebrow"><span className="pulse"></span> Curated opportunities, updated daily</div><h1>Good work<br/><i>finds you.</i></h1><p className="hero-copy">A calmer way to find freelance and remote work. No noise, no endless scrolling — just thoughtful opportunities worth your time.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by role, skill, or company"/><button onClick={()=>document.querySelector('#jobs').scrollIntoView({behavior:'smooth'})}>Find work <b>→</b></button></div><div className="hero-note"><span>✦</span> 1,240+ independent professionals use our alerts</div></section>
 <section className="signal"><div><span className="signal-number">01</span><strong>Signal over noise</strong><p>Every listing is screened for clarity, legitimacy, and a real opportunity to do meaningful work.</p></div><div><span className="signal-number">02</span><strong>Built for independent people</strong><p>Flexible roles, honest pay ranges, and remote-first teams — in one focused place.</p></div><div><span className="signal-number">03</span><strong>Arrive before the rush</strong><p>Fresh roles land in your inbox while they are still fresh, not after hundreds of applications.</p></div></section>
 <section className="jobs-section" id="jobs"><div className="section-head"><div><span className="label">THE LATEST</span><h2>Work worth<br/><i>looking at.</i></h2></div><a href="#newsletter" className="text-link">Get the weekly edit <span>↗</span></a></div><div className="filters"><div className="filter-label">Browse by focus</div>{skills.map(s=><button key={s} className={skill===s?'active':''} onClick={()=>setSkill(s)}>{s}</button>)}</div><div className="job-grid">{filtered.map(job=><article className="job-card" key={job.id}><div className="job-top"><span className="job-tag">{job.tag}</span><span className="job-time">{job.fresh}</span></div><h3>{job.title}</h3><p className="company">{job.company}</p><div className="job-meta"><span>{job.location}</span><span>{job.type}</span></div><div className="job-bottom"><strong>{job.pay}</strong><button aria-label={'View '+job.title}>↗</button></div></article>)}</div>{!filtered.length&&<div className="empty">No roles match that search yet. Try a different skill or keyword.</div>}<div className="more-row"><span>Showing {filtered.length} curated roles</span><button onClick={()=>{setQuery('');setSkill('All roles')}}>Reset filters ↺</button></div></section>
 <section className="manifesto" id="how"><div className="manifesto-mark">✳</div><div><span className="label">OUR PROMISE</span><h2>The internet has enough<br/><i>job boards.</i></h2><p>We are building something more useful: a considered layer between talented people and the teams looking for them. Fewer listings. Better signal. More room for the work itself.</p><a href="#newsletter" className="arrow-link">See what lands in your inbox <span>→</span></a></div></section>
 <section className="newsletter" id="newsletter"><div className="newsletter-copy"><span className="label light">THE WEEKLY EDIT</span><h2>Let the good ones<br/><i>come to you.</i></h2><p>A short, useful round-up of the best freelance and remote roles. Every Monday. No spam, ever.</p></div><form onSubmit={e=>{e.preventDefault(); if(email) setSubscribed(true)}}>{subscribed?<div className="success">✓ You’re on the list. See you Monday.</div>:<><label htmlFor="email">YOUR EMAIL ADDRESS</label><div className="email-row"><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/><button>Subscribe <span>→</span></button></div><small>By subscribing, you agree to receive the weekly edit. Unsubscribe anytime.</small></>}</form></section></main><footer><div className="brand footer-brand"><span className="brand-mark">FJ</span><span>Freelance<br/><em>Job Alerts</em></span></div><span>Made for people who make things.</span><div className="footer-links"><a href="#about">About</a><a href="#newsletter">Newsletter</a><a href="#top">Back to top ↑</a></div></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
